from typing import Any, Callable, Type, TypeVar

try:
    from typing import Protocol
except ImportError:
    _SupportsRead = Any
    _SupportsWrite = Any
else:
    class _SupportsRead(Protocol):
        def read(self, __size: int) -> bytes: ...

    class _SupportsWrite(Protocol):
        def write(self, __data: bytes) -> Any: ...

_T = TypeVar("_T")

__version__: str

version: tuple[int, int, int]

def pack(obj: Any, fp: _SupportsWrite, **options: Any) -> None: ...
def packb(obj: Any, **options: Any) -> bytes: ...
def dump(obj: Any, fp: _SupportsWrite, **options: Any) -> None: ...
def dumps(obj: Any, **options: Any) -> bytes: ...

def unpackb(s: bytes | bytearray, **options: Any) -> Any: ...
def unpack(fp: _SupportsRead, **options: Any) -> Any: ...
def loads(s: bytes | bytearray, **options: Any) -> Any: ...
def load(fp: _SupportsRead, **options: Any) -> Any: ...

class Ext:
    type: int
    data: bytes
    def __init__(self, type: int, data: bytes) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class InvalidString(bytes): ...

def ext_serializable(ext_type: int) -> Callable[[Type[_T]], Type[_T]]: ...

class PackException(Exception): ...
class UnpackException(Exception): ...
class UnsupportedTypeException(PackException): ...
class InsufficientDataException(UnpackException): ...
class InvalidStringException(UnpackException): ...
class UnsupportedTimestampException(UnpackException): ...
class ReservedCodeException(UnpackException): ...
class UnhashableKeyException(UnpackException): ...
class DuplicateKeyException(UnpackException): ...
KeyNotPrimitiveException = UnhashableKeyException
KeyDuplicateException = DuplicateKeyException

compatibility: bool
